name: Update Redirect Page

on:
  workflow_dispatch:

jobs:
  update-redirect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update index.html
        run: |
          sed "s|__VITE_API__|${{ secrets.VITE_API }}|g" docs/index.html > docs/index.html.tmp
          mv docs/index.html.tmp docs/index.html

      - name: Show index.html after replace (debug)
        run: |
          cat docs/index.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "Update redirect URL"
          git push
